### ISSUE TITLE
 compiling eval.s with gcc on OS X results in: Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by archived-aft-bogus-german-visa-rejectio** [melvinzhang/maru#3]
On OS X:

```
git show master:obj/eval.s | gcc -m32 -x assembler - -o bin/eval
Undefined symbols for architecture i386:
  "_main", referenced from:
     implicit entry/start for main executable
  "abort", referenced from:
      abort_24stub in --029b1b.o
     (maybe you meant: subr__abort)
  "exit", referenced from:
      exit_24stub in --029b1b.o
     (maybe you meant: subr__exit)
  "fclose", referenced from:
      fclose_24stub in --029b1b.o
  "fdopen", referenced from:
      fdopen_24stub in --029b1b.o
  "fflush", referenced from:
      fflush_24stub in --029b1b.o
  "fopen", referenced from:
      fopen_24stub in --029b1b.o
  "fprintf", referenced from:
      fprintf_24stub in --029b1b.o
  "free", referenced from:
      free_24stub in --029b1b.o
  "fscanf", referenced from:
      fscanf_24stub in --029b1b.o
  "getc", referenced from:
      getc_24stub in --029b1b.o
     (maybe you meant: subr__getc)
  "isatty", referenced from:
      isatty_24stub in --029b1b.o
  "malloc", referenced from:
      malloc_24stub in --029b1b.o
     (maybe you meant: gc__malloc, gc__malloc__atomic )
  "memcpy", referenced from:
      memcpy_24stub in --029b1b.o
  "memmove", referenced from:
      memmove_24stub in --029b1b.o
  "memset", referenced from:
      memset_24stub in --029b1b.o
  "printf", referenced from:
      printf_24stub in --029b1b.o
  "putc", referenced from:
      putc_24stub in --029b1b.o
     (maybe you meant: subr__putc)
  "realloc", referenced from:
      realloc_24stub in --029b1b.o
  "snprintf", referenced from:
      snprintf_24stub in --029b1b.o
  "sprintf", referenced from:
      sprintf_24stub in --029b1b.o
  "strcmp", referenced from:
      strcmp_24stub in --029b1b.o
  "strdup", referenced from:
      strdup_24stub in --029b1b.o
  "strlen", referenced from:
      strlen_24stub in --029b1b.o
  "strtoul", referenced from:
      strtoul_24stub in --029b1b.o
  "ungetc", referenced from:
      ungetc_24stub in --029b1b.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/eval] Error 1
```

[here is the gist of the src/osdefs.k](https://gist.github.com/0a-/5e88db4e9b91c6065ece).

**Comment by melvinzhang** [comment]
@0a- Thanks for the osdefs file. I've update the Makefile to be aware of OSX, it will now build bin/eval from obj/eval.osx.s. Please update and try running

```
make tests
```

If it is working properly, this will build bin/eval and run the tests.

**Comment by archived-aft-bogus-german-visa-rejectio** [comment]
@melvinzhang  ooh, thanks for the update! Just got it tested: it is running good :+1:  Looks like it passes all the tests:

```
bin/eval src/boot.l test/test-subr-logical.l
14342 objects in 157840 bytes, 1023056 free
bin/eval src/boot.l test/test-subr-relation.l
14342 objects in 157840 bytes, 1023056 free
bin/eval src/boot.l test/test-subr-binary.l
14342 objects in 157836 bytes, 973556 free
bin/eval src/boot.l test/test-subr.l
14342 objects in 157832 bytes, 1023432 free
bin/eval src/boot.l test/test-fsubr.l
14342 objects in 157832 bytes, 1023416 free
bin/eval src/boot.l test/test-boot.l
14342 objects in 157832 bytes, 1023432 free
```

However, when compiling the `eval.s`, I encountered this warning about position-independent executable:

> ld: warning: PIE disabled. Absolute addressing (perhaps -mdynamic-no-pic) not allowed in code signed PIE, but used in _main from /var/folders/9x/lxrcfbn11cxf31n7gkqqwr1h0000gn/T//ccPujLHd.o. To fix this warning, don't compile with -mdynamic-no-pic or link with -Wl,-no_pie

I tried compiling with `-fpic -pie`, and doing so with a newer-version of gcc (instead of the one shipped with mac) but I'm still getting the same warning. Not sure why somehow I cannot have PIE enabled. 

I just posted [a question on SO regarding it](http://stackoverflow.com/questions/32813653/how-not-to-compile-with-mdynamic-no-pic-when-using-gcc-on-os-x-to-enable-pie).

**Comment by melvinzhang** [comment]
I think this is because the compiler doesn't generate IA32 assembly that use a global offset table to load global values. 

No plans to improve the maru->IA32 compiler at this point, as the focus is on developing a maru->LLVM compiler which (hopefully) should not have this issue. Would compiling with -no_pie remove this warning?

**Comment by archived-aft-bogus-german-visa-rejectio** [comment]
Oooh. Cool!

Yup, there wouldn't be any warning when compiled with `-Wl,-no_pie`, though it'd still compile even when the warning is present.

**Comment by melvinzhang** [comment]
Thanks for confirming that the -Wl,-no_pie eliminates the warning, I'll add it to the call to gcc
